name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          VITE_LANGUAGE: en
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          VITE_SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          VITE_E2E_USER_EMAIL: ${{ secrets.E2E_USER_EMAIL }}
          VITE_E2E_USER_PASSWORD: ${{ secrets.E2E_USER_PASSWORD }}
          VITE_MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
          VITE_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

        with:
          start: npm run dev
          browser: chrome
      - name: Artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Screenshots
          path: cypress/screenshots
